services:
    photoprism:
        # Use photoprism/photoprism:preview instead for testing preview builds:
        image: photoprism/photoprism:latest
        container_name: photoprism
        # Only enable automatic restarts once your installation is properly
        # configured as it otherwise may get stuck in a restart loop:
        # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        ports:
            - 2342:2342 # [local port]:[container port]
        environment:
            PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
            PHOTOPRISM_ORIGINALS_LIMIT: 1000               # File size limit for originals in MB (increase for high-res video)
            PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
            PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
            PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
            PHOTOPRISM_READONLY: "true"                   # Don't modify originals directory (reduced functionality)
            PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
            PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
            PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
            PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
            PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
            PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
            PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
            # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
            PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
            PHOTOPRISM_DATABASE_SERVER: "photoprism-db:3306"     # MariaDB database server (hostname:port)
            PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
            PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
            PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB database user password
            PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public PhotoPrism URL
            PHOTOPRISM_SITE_TITLE: "PhotoPrism"
            PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
            PHOTOPRISM_SITE_DESCRIPTION: ""
            PHOTOPRISM_SITE_AUTHOR: ""
        # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
        # support this natively (see next example):
        # UID: 1000
        # GID: 1000
        # UMASK: 0000
        # Uncomment and edit the following line to set a specific user / group id (native):
        # user: "1000:1000"
        volumes:
            # Your photo and video files ([local path]:[container path]):
            - ${PATH_PHOTO}:/photoprism/originals:ro
            # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
            # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
            # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
            # Mounting an import folder is optional (see docs):
            # - "~/Import:/photoprism/import"
            # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
            - ./config:/photoprism/storage

    photoprism-db:
        image: mariadb:10.5
        container_name: photoprism-db
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
        volumes: # Don't remove permanent storage for index database files!
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: beenhad
            MYSQL_DATABASE: photoprism
            MYSQL_USER: photoprism
            MYSQL_PASSWORD: insecure          